version: "3.7"

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.6
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp 1                     # 최소 CPU 사용 (1코어)
      - --memory 256MB              # 최소 메모리 사용
      - --mode dev-container        # 개발 환경 최적화
      - --default-log-level=warn    # 로그 레벨을 경량화
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://43.201.55.18:19092
    ports:
      - 19092:19092
      - 9644:9644
    networks:
      - redpanda_network
    deploy:
      resources:
        limits:
          memory: "256MB"
          cpus: "0.2"
        reservations:
          memory: "128MB"

networks:
  redpanda_network:
    driver: bridge
