spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pawpatrol_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "${custom.dev.backUrl}/login/oauth2/code/{registrationId}"
          google:
            redirect-uri: "${custom.dev.backUrl}/login/oauth2/code/{registrationId}"
          naver:
            redirect-uri: "${custom.dev.backUrl}/login/oauth2/code/{registrationId}"
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: create

custom:
  oauth2:
    redirect-uri: http://localhost:5173/connect
  auth:
    redirect-uri: http://localhost:5173/login-pet
