name: AI Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'ai/**'
  workflow_dispatch:  # 수동 트리거 가능

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push AI service Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./ai
          file: ./ai/Dockerfile
          push: true
          tags: ghcr.io/your-username/pawpatrol-ai-service:latest

      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /dockerProjects/pawpatrol
            docker pull ghcr.io/your-username/pawpatrol-ai-service:latest
            docker tag ghcr.io/your-username/pawpatrol-ai-service:latest pawpatrol-ai-service:latest
            python3 ai_deploy.py
